#-------------------------------
# General Site Settings

title: WiWPH | WiWPH is Wendy's Personal Homepage
logo: logo.png # You can add own logo
description: # Add your awesome description
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

# Preloader
preloader: false # To disable preloader change value to false

menu:
  - url: /
    name: Home
  - url: /about/
    name: About
  - url: /categories/
    name: Categories
  #- url: /contact/
  #  name: Contact

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - url: /
#    name: Home
#  - url: /travel/
#    name: Travel
#     submenu:
#      - url: /peru/
#        name: Peru
# ----------------------------------

layout_home_page: false # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: Wendy's personal homepage #Iâ€™m a Freelance Interactive Art Director based in France. Focusing across branding and identity, digital and print.
  hero-banner: banner-img.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: Wendy

#-------------------------------
# Contact Info
contact:
  email1: wupengdi814@gmail.com
  email2: airguanz@gmail.com
#  phone: +123456789
#  address:
#    city: TODO
#    street: TODO

# Contact Form
#contact-form: TODO

# Social links
social:
- {icon: "ti-instagram", link: "https://github.com/"}

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor